src/Entity/Customer.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Table(name="customer")
 * @ORM\Entity(repositoryClass="App\Repository\CustomerRepository")
 */
class Customer extends User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     *
     */
    private $FirstName;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Demand", mappedBy="customer", orphanRemoval=true)
     */
    private $demands;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function getFullName(){
        return "{$this->FirstName} {$this->name}";
    }

    public function __construct()
    {
        $this->demands = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    /**
     * @return Collection|Demand[]
     */
    public function getDemands(): Collection
    {
        return $this->demands;
    }

    public function addDemand(Demand $demand): self
    {
        if (!$this->demands->contains($demand)) {
            $this->demands[] = $demand;
            $demand->setCustomer($this);
        }

        return $this;
    }

    public function removeDemand(Demand $demand): self
    {
        if ($this->demands->contains($demand)) {
            $this->demands->removeElement($demand);
            // set the owning side to null (unless already changed)
            if ($demand->getCustomer() === $this) {
                $demand->setCustomer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }



}

src/Entity/Provider.php
<?php

namespace App\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Table(name="provider")
 * @ORM\Entity(repositoryClass="App\Repository\ProviderRepository")
 */
class Provider extends User
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     */
    private $tva;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez renseigner une URL valide")
     */
    private $web;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="providers")
     */
    private $Service;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Execution", mappedBy="provider")
     */
    private $executions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="provider", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logoFilename;

    public function __construct()
    {
        $this->Service = new ArrayCollection();
        $this->executions = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTva(): ?string
    {
        return $this->tva;
    }

    public function setTva(?string $tva): self
    {
        $this->tva = $tva;

        return $this;
    }

    public function getWeb(): ?string
    {
        return $this->web;
    }

    public function setWeb(?string $web): self
    {
        $this->web = $web;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getService(): Collection
    {
        return $this->Service;
    }

    public function addService(Category $service): self
    {
        if (!$this->Service->contains($service)) {
            $this->Service[] = $service;
        }

        return $this;
    }

    public function removeService(Category $service): self
    {
        if ($this->Service->contains($service)) {
            $this->Service->removeElement($service);
        }

        return $this;
    }

    /**
     * @return Collection|Execution[]
     */
    public function getExecutions(): Collection
    {
        return $this->executions;
    }

    public function addExecution(Execution $execution): self
    {
        if (!$this->executions->contains($execution)) {
            $this->executions[] = $execution;
            $execution->setProvider($this);
        }

        return $this;
    }

    public function removeExecution(Execution $execution): self
    {
        if ($this->executions->contains($execution)) {
            $this->executions->removeElement($execution);
            // set the owning side to null (unless already changed)
            if ($execution->getProvider() === $this) {
                $execution->setProvider(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setProvider($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getProvider() === $this) {
                $comment->setProvider(null);
            }
        }

        return $this;
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à un provider
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author){
        foreach($this->comments as $comment){
            if($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }

    /**
     * Permet d'obtenir la moyenne globale des notes pour ce provider
     *
     * @return float|int
     */
    public function getAvgRatings(){
        // calcul de la somme des avis
        // array_reduce pour réduire le tableau de note à une seule valeur
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment){
            return $total + $comment->getRating();
        },0);

        // calcul de la moyenne
        if(count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }

    public function getLogoFilename(): ?string
    {
        return $this->logoFilename;
    }

    public function setLogoFilename(?string $logoFilename): self
    {
        $this->logoFilename = $logoFilename;

        return $this;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"provider" = "Provider", "customer" = "Customer"})
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Nom d'utilisateur déjà utilisé ( email )"
 * )
 */
abstract class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide !")
     */
    private $email;

    /**
     * @ORM\Column(type="datetime")
     */
    private $registration;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Vous n'avez pas correctement confirmé votre mot de passes !")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="boolean")
     */
    private $banished;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\PostalCode", inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $PostalCode;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Locality", inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $locality;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $siteRoles;

    public function __construct()
    {
        $this->siteRoles = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRegistration(): ?\DateTimeInterface
    {
        return $this->registration;
    }

    public function setRegistration(\DateTimeInterface $registration): self
    {
        $this->registration = $registration;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getBanished(): ?bool
    {
        return $this->banished;
    }

    public function setBanished(bool $banished): self
    {
        $this->banished = $banished;

        return $this;
    }

    public function getPostalCode(): ?PostalCode
    {
        return $this->PostalCode;
    }

    public function setPostalCode(?PostalCode $PostalCode): self
    {
        $this->PostalCode = $PostalCode;

        return $this;
    }

    public function getLocality(): ?Locality
    {
        return $this->locality;
    }

    public function setLocality(?Locality $locality): self
    {
        $this->locality = $locality;

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->siteRoles->map(function($role){
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        /*dump($roles);
        die();*/

        return $roles;
    }

    public function getSalt(){

    }

    public function getUsername(){
        return $this->email;
    }

    public function eraseCredentials()
    {

    }

    /**
     * @return Collection|Role[]
     */
    public function getSiteRoles(): Collection
    {
        return $this->siteRoles;
    }

    public function addSiteRole(Role $siteRole): self
    {
        if( is_null( $this->siteRoles)){
            $this->siteRoles = new ArrayCollection();

        }
        if (!$this->siteRoles->contains($siteRole)) {
            $this->siteRoles[] = $siteRole;
            $siteRole->addUser($this);
        }

        return $this;

    }

    public function removeSiteRole(Role $siteRole): self
    {
        if ($this->siteRoles->contains($siteRole)) {
            $this->siteRoles->removeElement($siteRole);
            $siteRole->removeUser($this);
        }

        return $this;
    }

}

templates/profile/demands.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre historique de demandes de services{% endblock %}

{% block body %}
    {% block content %}


        <div class="sub_header_in sticky_header">
            <div class="container">
                <h1>Mes demandes de services</h1>
            </div>
            <!-- /container -->
        </div>
        <!-- /sub_header -->

        <main>
            <div class="container margin_60_35">
                <div class="box_booking">
                    {% if app.user.demands|length >0 %}
                    {% for demand in app.user.demands %}

                        <div class="strip_booking">
                            <div class="row">
                            {#{% for execution in executions %}#}
                                <div class="col-lg-2 col-md-2">
                                    <div class="date">
                                        <span class="month">Proposition n° {{ demand.id }}</span>
                                        <span class="day">Image</span>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-5">
                                    <h3>{{ demand.title }}</h3>

                                </div>
                                <div class="col-lg-2 col-md-3">
                                    <ul class="info_booking">

                                        {% for execution in executions %}
                                            <li><strong>Par : {{ execution.provider.name }}</strong></li>
                                        {% endfor %}
                                    </ul>
                                </div>

                                <div class="col-lg-2 col-md-2">
                                    <div class="booking_buttons">
                                        {#<a href="{{ path('execution_show', {'id':execution.id}) }}" class="btn_2">Info</a>#}
                                        <a href="#" class="btn_2">Info</a>
                                        <a href="#" class="btn_3">Supprimer</a>
                                    </div>
                                </div>

                            </div>

                            <!-- /row -->
                        </div>
                    {% endfor %}
                {% else %}
                     Vous n'avez pas encore déposé de demande
                {% endif %}



                </div>
                <!-- /box_booking -->
                {#<p class="text-right"><a href="checkout.html" class="btn_1">Checkout</a></p>#}
            </div>
            <!-- /container -->
        </main>
        <!--/main-->


        </div>
        <!-- page -->
    {% endblock %}
{% endblock %}

templates/profile/detailspro.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail du prestaire{% endblock %}

{% block body %}
    {% block content %}
    <div class="hero_in hotels_detail">
        <div class="wrapper">
				<span class="magnific-gallery">
					<a href="img/gallery/hotel_list_1.jpg" class="btn_photos" title="Photo title" data-effect="mfp-zoom-in">View photos</a>
					<a href="img/gallery/hotel_list_2.jpg" title="Photo title" data-effect="mfp-zoom-in"></a>
					<a href="img/gallery/hotel_list_3.jpg" title="Photo title" data-effect="mfp-zoom-in"></a>
				</span>
        </div>
    </div>
    <!--/hero_in-->

    <nav class="secondary_nav sticky_horizontal_2">
        <div class="container">
            <ul class="clearfix">
                <li><a href="#description" class="active">Description</a></li>
                <li><a href="#reviews">Reviews</a></li>
                <li><a href="#sidebar">Booking</a></li>
            </ul>
        </div>
    </nav>

    <div class="container margin_60_35">
        <div class="row">
            <div class="col-lg-12">
                <section id="description">
                    <div class="detail_title_1">

                        <h1>{{ provider.name }}</h1>
                        <span>{{ provider.address }}</span></br>
                        <span>{{ provider.PostalCode }} {{ provider.locality }}</span></br>
                        <span>Tel.: {{ provider.phone }}</span></br>
                        <span>Email: <a href="mailto:{{ provider.email }}">{{ provider.email }}</a></span></br>
                        <span>Site Web: <a href="{{ provider.web }}">{{ provider.web }}</a></span></br>
                        <span>TVA: {{ provider.tva }}</span>

                    </div>
                    <p>Per consequat adolescens ex, cu nibh commune <strong>temporibus vim</strong>, ad sumo viris eloquentiam sed. Mea appareat omittantur eloquentiam ad, nam ei quas oportere democritum. Prima causae admodum id est, ei timeam inimicus sed. Sit an meis aliquam, cetero inermis vel ut. An sit illum euismod facilisis, tamquam vulputate pertinacia eum at.</p>
                    <p>Cum et probo menandri. Officiis consulatu pro et, ne sea sale invidunt, sed ut sint <strong>blandit</strong> efficiendi. Atomorum explicari eu qui, est enim quaerendum te. Quo harum viris id. Per ne quando dolore evertitur, pro ad cibo commune.</p>
                    <h5 class="add_bottom_15">Catégorie(s) de service</h5>
                    <div class="row add_bottom_30">
                        <div class="col-lg-6">
                            <ul class="bullets">
                                {% for category in provider.service %}
                                <li>{{ category.name }}</li>
                                {% endfor %}

                            </ul>
                        </div>

                    </div>
                    <!-- /row -->

                    <hr>

                    <h3>Location</h3>
                    <div id="map" class="map map_single add_bottom_45"></div>
                    <!-- End Map -->
                </section>
                <!-- /section -->

                <section id="reviews">
                    {% if provider.comments|length > 0%}

                    <div class="reviews-container add_bottom_30">
                        <div class="row">
                            <div class="col-lg-12">
                                <div id="review_summary">
                                    <div class="col">
                                        Note moyenne donnée par les utilisateurs
                                    </div>
                                    <div class="col">
                                        <strong>{% include 'partials/rating.html.twig' with {'rating' : provider.avgRatings} %}</strong>
                                             <small>Basé sur {{ provider.comments|length }} avis</small>
                                    </div>

                                </div>
                            </div>

                        </div>
                        <!-- /row -->
                    </div>

                    <div class="reviews-container">
                        {#{% if provider.comments|length > 0%}#}
                            {% for comment in provider.comments %}
                                <div class="review-box clearfix">
                                    <figure class="rev-thumb"><img src="img/avatar1.jpg" alt="">
                                    </figure>
                                    <div class="rev-content">
                                        <strong>Niveau de satisfaction : </strong>
                                        {# utilisation du template rating avec passage de variable #}
                                        {% include 'partials/rating.html.twig' with {'rating': comment.rating}%}

                                        <div class="rev-info">
                                            {{ comment.author.fullName }} – Date de publication :
                                        </div>
                                        <div class="rev-text">
                                            <p>
                                                {{ comment.content }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}

                        {#{% endif %}#}


                        <!-- /review-box -->


                    </div>
                    <!-- /review-container -->
                    {% endif %}
                </section>
                <!-- /section -->
                <hr>

                <div class="add-review">
                    <h5>Laissez-nous un message</h5>
                    <form>
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label>Name and Lastname *</label>
                                <input type="text" name="name_review" id="name_review" placeholder="" class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label>Email *</label>
                                <input type="email" name="email_review" id="email_review" class="form-control">
                            </div>
                            <div class="form-group col-md-6">
                                <label>Rating </label>
                                <div class="custom-select-form">
                                    <select name="rating_review" id="rating_review" class="wide">
                                        <option value="1">1 (lowest)</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5" selected>5 (medium)</option>
                                        <option value="6">6</option>
                                        <option value="7">7</option>
                                        <option value="8">8</option>
                                        <option value="9">9</option>
                                        <option value="10">10 (highest)</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label>Your Review</label>
                                <textarea name="review_text" id="review_text" class="form-control" style="height:130px;"></textarea>
                            </div>
                            <div class="form-group col-md-12 add_top_20 add_bottom_30">
                                <input type="submit" value="Submit" class="btn_1" id="submit-review">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /col -->


        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
    {% endblock %}
{% endblock %}

templates/profile/executions.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre historique de propositions de services{% endblock %}

{% block body %}
    {% block content %}


    <div class="sub_header_in sticky_header">
        <div class="container">
            <h1>Mes propositions de services</h1>
        </div>
        <!-- /container -->
    </div>
    <!-- /sub_header -->

    <main>
        <div class="container margin_60_35">
            <div class="box_booking">
        {% if app.user.executions|length >0 %}
            {% for execution in app.user.executions %}
                <div class="strip_booking">
                    <div class="row">
                        <div class="col-lg-2 col-md-2">
                            <div class="date">
                                <span class="month">Proposition n° {{ execution.id }}</span>
                                <span class="day">Image</span>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-5">
                            <h3>{{ execution.demand.title }}</h3>
                            <h3>Demandeur : {{ execution.demand.customer.fullName }}</h3>
                        </div>
                        <div class="col-lg-2 col-md-3">
                            <ul class="info_booking">

                                <li><strong>Du</strong> {{execution.startDate|date('d/m/y')}} <strong>au</strong> {{execution.enDate|date('d/m/y') }}</li>
                            </ul>
                        </div>
                        <div class="col-lg-2 col-md-2">
                            <div class="booking_buttons">
                                <a href="{{ path('execution_show', {'id':execution.id}) }}" class="btn_2">Info</a>
                                <a href="#" class="btn_3">Supprimer</a>
                            </div>
                        </div>
                    </div>
                    <!-- /row -->
                </div>
            {% endfor %}
        {% else %}
            Aucune proposition de services en cours
        {% endif %}



            </div>

        </div>
        <!-- /container -->
    </main>
    <!--/main-->


</div>
<!-- page -->
    {% endblock %}
{% endblock %}

templates/profile/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProfileController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp/www/tfe/Mytfe/src/Controller/ProfileController.php'|file_link(0) }}">src/Controller/ProfileController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp/www/tfe/Mytfe/templates/profile/index.html.twig'|file_link(0) }}">templates/profile/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/profile/listpro.html.twig
{% extends 'base_listing.html.twig' %}

{% block title %}Liste des prestaires{% endblock %}

{% block body %}
    {% block content %}

    <div class="row">
        {% for provider in providers %}
        <div class="col-xl-4 col-lg-6 col-md-6">
            <div class="strip grid">
                <figure>

                    {% if (provider.logoFilename is null) %}

                        <img src="{{ asset('assets/img/logos/logo_not_found.jpg' | imagine_filter('squared_thumbnail_small') ) }}" />
                    {% else %}
                        <a href="#"><img src="/assets/img/logos/{{ provider.logoFilename }}" ><div class="read_more"><span>En savoir plus ...</span></div></a>
                    {% endif %}
                        {% for category in provider.service %}
                            <small>{{ category.name }}</small>
                        {% endfor %}
                </figure>
                <div class="wrapper">
                    {#{% set url = path('provider_show',{'id':provider.id}) %}#}
                    {#<h3><a href="{{ url }}">{{ provider.name }}</a></h3>#}
                    <h3><a href="#">{{ provider.name }}</a></h3>

                        <p>{{ provider.address }} <br/>
                        {{ provider.postalCode }} - {{ provider.locality }} <br/>
                        <b>Tel.:</b> {{ provider.phone }}<br/>
                        <b>Email:</b> <a href="mailto:{{ provider.email }}">{{ provider.email }}</a></p>


                    <a href="{{ provider.web }}" target="_blank">{{ provider.web }}</a>
                </div>
                <ul>
                    {#<li><span class="loc_open">Now Open</span></li>#}
                    {% if provider.comments|length >0 %}
                        {% include 'partials/rating.html.twig' with {'rating': provider.avgRatings} %}
                    {% else %}
                        <small>Pas encore noté</small>
                    {% endif %}
                    {#<li><div class="score"><span>Superb<em>350 Reviews</em></span><strong>8.9</strong></div></li>#}
                </ul>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}
{% endblock %}

templates/profile/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %} Modification de votre compte Pro{% endblock %}

{% block body %}
    {% block content %}
        <div class="container">
            <h1>- Modification de votre compte Pro -</h1>

            <hr>

                {{ form_start(form) }}
                {{ form_widget(form) }}
                {{ form_end(form) }}


        </div>

    {% endblock %}
{% endblock %}

templates/profile/profile_user.html.twig
{% extends 'base.html.twig' %}

{% block title %} Modification de votre compte{% endblock %}

{% block body %}
    {% block content %}
        <div class="container">
            <h1>- Modification de votre compte -</h1>
            <hr>

            {{ form_start(form) }}
            {{ form_widget(form) }}
            {{ form_end(form) }}

            <div class="row">

                <h1> Mes annonces : </h1>

            </div>
        </div>

    {% endblock %}
{% endblock %}